# Phase 1: Exploring the World Bank API

**Goal:** understand the source data *before* writing the pipeline. By the end you should be able to explain what one record means, how paging works, and which indicators have gaps.

**How to use this notebook:** run cells top to bottom with **Shift + Enter**. Read the markdown under each output: it tells you what to look for. Answer the questions in the *Your notes* cell at the end.

**Updated after the extension:** the project started with 4 indicators and now has 9. The cells read the list from `config/indicators.yml`, so they cover all 9 automatically. Section 9 shows how the 5 new ones were chosen.

Kernel check: the top-right of Jupyter should say **Python (econdev)**. If not, use *Kernel → Change kernel*.

## 1. Setup

We read countries, years and indicator codes from `config/indicators.yml` instead of typing them here. The ingestion script will read the same file, so the notebook and the pipeline can never disagree about scope.

In [1]:
import json
from pathlib import Path

import pandas as pd
import requests
import yaml

config = yaml.safe_load(Path("../config/indicators.yml").read_text())
COUNTRIES = config["countries"]
START, END = config["start_year"], config["end_year"]
INDICATORS = config["indicators"]          # {code: friendly_name}

BASE_URL = "https://api.worldbank.org/v2"
print("Countries:", COUNTRIES)
print("Years:", START, "to", END)
print("Indicators:", INDICATORS)

Countries: ['NGA', 'KEN', 'GHA', 'RWA', 'ZAF']
Years: 2000 to 2025
Indicators: {'NY.GDP.MKTP.KD.ZG': 'gdp_growth_pct', 'SI.POV.DDAY': 'poverty_pct', 'IT.CEL.SETS.P2': 'mobile_per_100', 'SL.UEM.TOTL.ZS': 'unemployment_pct', 'NY.GDP.PCAP.KD.ZG': 'gdp_per_capita_growth_pct', 'SL.EMP.VULN.ZS': 'vulnerable_employment_pct', 'SI.DST.FRST.20': 'income_share_bottom20_pct', 'EG.ELC.ACCS.ZS': 'electricity_access_pct', 'SP.DYN.LE00.IN': 'life_expectancy_years'}

## 2. One request, raw

An API call is just an HTTP GET to a URL with some parameters. Let's make one and look at what comes back **before** turning it into a table.

In [2]:
url = f"{BASE_URL}/country/{';'.join(COUNTRIES)}/indicator/NY.GDP.MKTP.KD.ZG"
params = {"format": "json", "per_page": 1000, "date": f"{START}:{END}"}

resp = requests.get(url, params=params, timeout=30)
print("Status code:", resp.status_code)     # 200 = OK
print("Full URL:", resp.url)

body = resp.json()
print("Top-level type:", type(body).__name__, "with", len(body), "items")

Status code: 200
Full URL: https://api.worldbank.org/v2/country/NGA;KEN;GHA;RWA;ZAF/indicator/NY.GDP.MKTP.KD.ZG?format=json&per_page=1000&date=2000%3A2025
Top-level type: list with 2 items

**What to notice:** the response is a list of **2 items**, not a single object. That's a World Bank quirk. Item 0 is page metadata, item 1 is the actual records.

In [3]:
meta, records = body
meta

{'page': 1,
 'pages': 1,
 'per_page': 1000,
 'total': 130,
 'sourceid': '2',
 'lastupdated': '2026-10-08'}

**What to notice:** `total` is the number of records across all pages (5 countries × 26 years = 130). `pages` tells you whether you need to ask for more. `lastupdated` is when the World Bank last revised this indicator: worth keeping, because past values can change.

## 3. One record up close

Before writing any SQL you need to know the **grain**: what does one record represent?

In [4]:
print(json.dumps(records[0], indent=2))

{
  "indicator": {
    "id": "NY.GDP.MKTP.KD.ZG",
    "value": "GDP growth (annual %)"
  },
  "country": {
    "id": "GH",
    "value": "Ghana"
  },
  "countryiso3code": "GHA",
  "date": "2025",
  "value": 5.95441714756899,
  "unit": "",
  "obs_status": "",
  "decimal": 1
}

**What to notice:**
- One record = **one country, one indicator, one year**. That's the grain of your staging model.
- `indicator` and `country` are *nested* objects (each has an `id` and a `value`).
- `date` is a **string** (`"2025"`), not a number. Staging will need to cast it.
- `country.id` is a 2-letter code but `countryiso3code` is 3 letters. Pick one and use it everywhere (the config uses 3-letter codes).
- `value` can be `null`. Run the next cell to see how often.

In [5]:
df = pd.json_normalize(records)    # flattens nested JSON: country.value -> 'country.value' column
print(df.dtypes, "\n")
df.head()

countryiso3code        str
date                   str
value              float64
unit                   str
obs_status             str
decimal              int64
indicator.id           str
indicator.value        str
country.id             str
country.value          str
dtype: object

,countryiso3code,date,value,unit,obs_status,decimal,indicator.id,indicator.value,country.id,country.value
0,GHA,2025,5.954417,,,1,NY.GDP.MKTP.KD.ZG,GDP growth (annual %),GH,Ghana
1,GHA,2024,5.847469,,,1,NY.GDP.MKTP.KD.ZG,GDP growth (annual %),GH,Ghana
2,GHA,2023,3.140091,,,1,NY.GDP.MKTP.KD.ZG,GDP growth (annual %),GH,Ghana
3,GHA,2022,3.804850,,,1,NY.GDP.MKTP.KD.ZG,GDP growth (annual %),GH,Ghana
4,GHA,2021,5.076466,,,1,NY.GDP.MKTP.KD.ZG,GDP growth (annual %),GH,Ghana

**What to notice:** `pd.json_normalize` turned the nested objects into dotted column names like `country.value`. In BigQuery you'll do the same thing with `JSON_VALUE(payload, '$.country.value')`. Also check the dtypes: `date` came through as `str` (text), not a number.

## 4. Pagination

APIs rarely return everything in one go. Here we deliberately ask for small pages to see how it works.

In [6]:
small = requests.get(url, params={**params, "per_page": 50}, timeout=30).json()
small[0]

{'page': 1,
 'pages': 3,
 'per_page': 50,
 'total': 130,
 'sourceid': '2',
 'lastupdated': '2026-10-08'}

Now `pages` is 3. To get everything you must request `page=1`, `page=2`, `page=3` and combine them. The loop below is exactly what `worldbank_client.py` will do in Phase 2.

In [7]:
def fetch_all_pages(url, params):
    records, page = [], 1
    while True:
        meta, rows = requests.get(url, params={**params, "page": page}, timeout=30).json()
        records.extend(rows or [])
        print(f"page {page} of {meta['pages']}: {len(rows or [])} records")
        if page >= meta["pages"]:
            return records
        page += 1


paged = fetch_all_pages(url, {**params, "per_page": 50})
print("Total collected:", len(paged))

page 1 of 3: 50 records

page 2 of 3: 50 records

page 3 of 3: 30 records
Total collected: 130

**Check:** the total should match `meta["total"]` from section 2. If a pipeline forgets to page, it silently loads only the first page, and nothing errors. That's one of the most common ingestion bugs.

## 5. All indicators: how complete is the data?

Now pull every indicator in the config and count how many years actually have a value. This **coverage table** is one of the most useful things you can make when you meet a new dataset.

In [8]:
frames = []
for code, name in INDICATORS.items():
    recs = fetch_all_pages(f"{BASE_URL}/country/{';'.join(COUNTRIES)}/indicator/{code}",
                           {**params, "per_page": 1000})
    frame = pd.json_normalize(recs)
    frame["indicator_name"] = name
    frames.append(frame)

all_df = pd.concat(frames, ignore_index=True)
expected = len(COUNTRIES) * len(INDICATORS) * (END - START + 1)
print("Rows:", len(all_df), f"(expect {len(COUNTRIES)} countries x {len(INDICATORS)} indicators x {END - START + 1} years = {expected})")

coverage = (all_df.assign(has_value=all_df["value"].notna())
                  .pivot_table(index="countryiso3code", columns="indicator_name",
                               values="has_value", aggfunc="sum"))
coverage

page 1 of 1: 130 records

page 1 of 1: 130 records

page 1 of 1: 130 records

page 1 of 1: 130 records

page 1 of 1: 130 records

page 1 of 1: 130 records
page 1 of 1: 130 records

page 1 of 1: 130 records

page 1 of 1: 130 records
Rows: 1170 (expect 5 countries x 9 indicators x 26 years = 1170)

indicator_name,electricity_access_pct,gdp_growth_pct,gdp_per_capita_growth_pct,income_share_bottom20_pct,life_expectancy_years,mobile_per_100,poverty_pct,unemployment_pct,vulnerable_employment_pct
countryiso3code,,,,,,,,,
GHA,25,26,26,3,25,25,3,26,26
KEN,25,26,26,5,25,25,5,26,26
NGA,25,26,26,6,25,25,6,26,26
RWA,25,26,26,6,25,25,6,26,26
ZAF,25,26,26,6,25,25,6,26,26

**What to notice:**
- Most indicators have 25–26 years per country. The ones with 25 (mobile, electricity, life expectancy) are missing 2025 because the World Bank hasn't published it yet.
- **`poverty_pct` and `income_share_bottom20_pct` have only 3–6 values each.** Both come from household surveys, which happen every few years.

That gap shapes the whole project: you can't compare poverty year by year, only between survey years.

## 6. Poverty deep dive

This is the cell you wrote: only the years where a poverty survey actually exists.

In [9]:
url = "https://api.worldbank.org/v2/country/NGA;KEN;GHA;RWA;ZAF/indicator/SI.POV.DDAY"
meta, records = requests.get(url, params={"format": "json", "per_page": 1000, "date": "2000:2025"}).json()

df = pd.json_normalize(records)                      # flattens nested JSON into columns
df[df["value"].notna()][["countryiso3code", "date", "value"]]   # only the years with real data

    countryiso3code  date  value
9               GHA  2016   39.0
13              GHA  2012   41.8
20              GHA  2005   60.9
29              KEN  2022   45.5
30              KEN  2021   46.4
31              KEN  2020   44.4
36              KEN  2015   37.7
46              KEN  2005   44.6
55              NGA  2022   41.8
59              NGA  2018   34.2
62              NGA  2015   35.8
65              NGA  2012   37.4
67              NGA  2010   38.5
74              NGA  2003   51.1
80              RWA  2023   38.6
87              RWA  2016   63.8
90              RWA  2013   65.2
93              RWA  2010   70.2
98              RWA  2005   74.2
103             RWA  2000   82.3
107             ZAF  2022   17.4
115             ZAF  2014   27.9
119             ZAF  2010   27.8
121             ZAF  2008   37.0
124             ZAF  2005   40.7
129             ZAF  2000   47.9

**What to notice:** the survey years differ by country (Ghana's latest is 2016, Rwanda's is 2023). To compare countries fairly, the analysis will look at the *change* between two survey years against average GDP growth over the same span.

## 6b. Do the two survey indicators line up?

The poorest 20%'s income share also comes from household surveys. If it was measured in **exactly the same years** as poverty, we can put both into the survey-to-survey mart. If not, joining them would create gaps. Check before you join.

In [10]:
share_url = f"{BASE_URL}/country/{';'.join(COUNTRIES)}/indicator/SI.DST.FRST.20"
share = pd.json_normalize(fetch_all_pages(share_url, {**params, "per_page": 1000}))

pov_years = set(df.loc[df["value"].notna(), ["countryiso3code", "date"]].itertuples(index=False, name=None))
share_years = set(share.loc[share["value"].notna(), ["countryiso3code", "date"]].itertuples(index=False, name=None))

print("Survey years with poverty only:", sorted(pov_years - share_years))
print("Survey years with the share only:", sorted(share_years - pov_years))
print("Survey years with both:", len(pov_years & share_years))

page 1 of 1: 130 records
Survey years with poverty only: []
Survey years with the share only: []
Survey years with both: 26

**What to notice:** both "only" lists are empty, so every poverty survey also has the poorest 20%'s share, and vice versa. They're two results from the same surveys. That's why the share can sit next to poverty in `fct_poverty_survey_spans`, and why a `not_null` test there protects the assumption.

## 7. What does each indicator actually measure?

The API also describes each indicator. Read these: they go straight into your dbt column descriptions and README.

In [11]:
for code in INDICATORS:
    info = requests.get(f"{BASE_URL}/indicator/{code}", params={"format": "json"}, timeout=30).json()[1][0]
    print(f"{code}: {info['name']}")
    print(f"  Source: {info['sourceOrganization'][:150]}")
    print(f"  Note: {info['sourceNote'][:300]}...\n")

NY.GDP.MKTP.KD.ZG: GDP growth (annual %)
  Source: Country official statistics, National Statistical Organizations and/or Central Banks;
National Accounts data files, Organisation for Economic Co-opera
  Note: Gross domestic product is the total income earned through the production of goods and services in an economic territory during an accounting period. It can be measured in three different ways: using either the expenditure approach, the income approach, or the production approach. This indicator deno...

SI.POV.DDAY: Poverty headcount ratio at $3.00 a day (2021 PPP) (% of population)
  Source: World Bank, Poverty and Inequality Platform. Data are based on primary household survey data obtained from government statistical agencies and World B
  Note: Poverty headcount ratio at $3.00 a day is the percentage of the population living on less than $3.00 a day at 2021 purchasing power adjusted prices. As a result of revisions in PPP exchange rates, poverty rates for individual countries cannot be compared with poverty rates reported in earlier editio...

IT.CEL.SETS.P2: Mobile cellular subscriptions (per 100 people)
  Source: World Telecommunication/ICT Indicators Database, International Telecommunication Union (ITU)
  Note: Mobile cellular telephone subscriptions are subscriptions to a public mobile telephone service that provide access to the PSTN using cellular technology. The indicator includes (and is split into) the number of postpaid subscriptions, and the number of active prepaid accounts (i.e. that have been us...

SL.UEM.TOTL.ZS: Unemployment, total (% of total labor force) (modeled ILO estimate)
  Source: ILO Modelled Estimates database (ILOEST), International Labour Organization (ILO), uri: https://ilostat.ilo.org/data/bulk/, publisher: ILOSTAT, type:
  Note: Unemployment refers to the share of the labor force that is without work but available for and seeking employment....

NY.GDP.PCAP.KD.ZG: GDP per capita growth (annual %)
  Source: Country official statistics, National Statistical Organizations and/or Central Banks;
National Accounts data files, Organisation for Economic Co-opera
  Note: Gross domestic product is the total income earned through the production of goods and services in an economic territory during an accounting period. It can be measured in three different ways: using either the expenditure approach, the income approach, or the production approach. The core indicator ...

SL.EMP.VULN.ZS: Vulnerable employment, total (% of total employment) (modeled ILO estimate)
  Source: ILO Modelled Estimates database (ILOEST), International Labour Organization (ILO), uri: https://ilostat.ilo.org/data/bulk/, publisher: ILOSTAT, type:
  Note: Vulnerable employment is contributing family workers and own-account workers as a percentage of total employment....

SI.DST.FRST.20: Income share held by lowest 20%
  Source: World Bank, Poverty and Inequality Platform. Data are based on primary household survey data obtained from government statistical agencies and World B
  Note: Percentage share of income or consumption is the share that accrues to subgroups of population indicated by deciles or quintiles. Percentage shares by quintile may not sum to 100 because of rounding....

EG.ELC.ACCS.ZS: Access to electricity (% of population)
  Source: SDG 7.1.1 Electrification Dataset, World Bank (WB), uri: https://trackingsdg7.esmap.org/downloads, note: Data is downloaded from ESMAP website. Data i
  Note: Access to electricity is the percentage of population with access to electricity. Electrification data are collected from industry, national surveys and international sources....

SP.DYN.LE00.IN: Life expectancy at birth, total (years)
  Source: World Population Prospects, United Nations (UN), uri: UN Population Division;
Statistical databases and publications from national statistical offices
  Note: Life expectancy at birth indicates the number of years a newborn infant would live if prevailing patterns of mortality at the time of its birth were to stay the same throughout its life....

## 8. Your notes

Double-click this cell and answer in your own words. These become the *Data* section of your README.

1. What does one record represent (the grain)?
2. Which fields need cleaning or type casting in staging?
3. Which indicator has gaps, and how will you handle them?
4. Why does pagination matter, even though our data fits on one page?
5. Anything that surprised you?

My answers:
1. The grain is one indicator, one country, one year
2. The year need to be cast as interger
3. Poverty has gap, i think we will assume the same poverty rate may need to be repeated across years up to the time it changes, same for mobile per 100
4. pagination is important in order to load all the data
5. The incomplete data perhaps of some indicators like poverty rate and mobile per 100

## 9. Choosing new indicators: profile before you add

The first version answered the question with 4 indicators, and its limitations listed what was missing: growth per person, who benefits, job quality, living standards and health. Before adding anything to the config, each candidate was checked for **coverage in all 5 countries**. An indicator missing for one country would put a footnote on every comparison.

In [12]:
candidates = {
    "NY.GDP.PCAP.KD.ZG": "GDP growth per person",
    "SI.DST.FRST.20": "Income share of the poorest 20%",
    "SL.EMP.VULN.ZS": "Vulnerable employment",
    "EG.ELC.ACCS.ZS": "Access to electricity",
    "SP.DYN.LE00.IN": "Life expectancy",
    "NE.CON.PRVT.PC.KD": "Household consumption per person",
    "SE.PRM.CMPT.ZS": "Primary completion rate",
}

rows = []
for code, label in candidates.items():
    recs = fetch_all_pages(f"{BASE_URL}/country/{';'.join(COUNTRIES)}/indicator/{code}", {**params, "per_page": 1000})
    frame = pd.json_normalize(recs)
    counts = frame[frame["value"].notna()].groupby("countryiso3code").size()
    rows.append({"indicator": label, "code": code, **{c: int(counts.get(c, 0)) for c in COUNTRIES}})

candidate_coverage = pd.DataFrame(rows).set_index("indicator")
candidate_coverage

page 1 of 1: 130 records

page 1 of 1: 130 records
page 1 of 1: 130 records

page 1 of 1: 130 records
page 1 of 1: 130 records

page 1 of 1: 130 records

page 1 of 1: 130 records

                                               code  NGA  KEN  GHA  RWA  ZAF
indicator
GDP growth per person             NY.GDP.PCAP.KD.ZG   26   26   26   26   26
Income share of the poorest 20%      SI.DST.FRST.20    6    5    3    6    6
Vulnerable employment                SL.EMP.VULN.ZS   26   26   26   26   26
Access to electricity                EG.ELC.ACCS.ZS   25   25   25   25   25
Life expectancy                      SP.DYN.LE00.IN   25   25   25   25   25
Household consumption per person  NE.CON.PRVT.PC.KD    0   26   19   26   26
Primary completion rate              SE.PRM.CMPT.ZS    8    5   20   19   12

**What to notice:**
- The first five have full coverage (or, for the poorest 20%'s share, the same survey years as poverty). **These were added.**
- **Household consumption per person has no Nigeria data at all.** It's arguably the best living-standards measure, but one of the five countries would be blank in every chart, so it was rejected.
- **Primary completion is patchy:** Kenya has only a handful of years. Also rejected.

Adding the five took config lines, a staging mapping, pivot columns and tests. The ingestion code didn't change, because it reads its scope from the config.